#!/usr/bin/env python
from sys import argv
from time import sleep


def main(fruit = None):
    print("hmm… ", end = "", flush = True)
    sleep(2)

    match fruit:
        case "grape":
            print("purple, or maybe green")
        case "peach":
            print("yellow")
        case "rhubarb":
            print("red")
        case _:
            print("I dunno!")


if __name__ == "__main__":
    main(*argv[1:])
