name: Test

on:
  workflow_dispatch:
    inputs:

jobs:
  test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - run: ./whatcoloris grape
      - run: ./whatcoloris papaya
      - run: ./whatcoloris pineapple

      - if: failure()
        uses: nextstrain/.github/actions/setup-ssh@master
        with:
          tailscale-auth-key: ${{ secrets.TAILSCALE_AUTH_KEY }}
          wait-for-continue: true
