name: Test

on:
  workflow_dispatch:
    inputs:

jobs:
  test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - run: python --version
      - run: ./whatcoloris grape
      - run: ./whatcoloris papaya
      - run: ./whatcoloris pineapple
