name: Test

on:
  workflow_dispatch:
    inputs:

jobs:
  test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: nextstrain/.github/actions/setup-debugger@master
        with:
          tailscale-auth-key: ${{ secrets.TAILSCALE_AUTH_KEY }}

      - run: ./whatcoloris grape
      - run: ./whatcoloris papaya
      - run: ./whatcoloris pineapple
